# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 02:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_usertestresults_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestresults',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
