# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20170407_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='img1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='sampleImages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='img2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='sampleImages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='img3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='sampleImages'),
            preserve_default=False,
        ),
    ]
